ERROR > An Error Occured
Traceback (most recent call last):
  File "bot.py", line 38, in <module>
    exec(rk.read())
  File "<string>", line 2, in <module>
AttributeError: module 'discord' has no attribute 'Menber'
